name: positio_test
description: "Parmet de localiser tous les employes."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  gap: ^3.0.1
  sizer: ^2.0.15
  intl: ^0.19.0
  intl_phone_number_input:
    git:
      url: https://github.com/Shahidbangash/intl_phone_number_input.git
      ref: develop
  shared_preferences: ^2.3.2
  http: ^1.2.2
  connectivity_plus: ^6.0.3
  google_maps_flutter: ^2.6.1
  flutter_map: ^6.1.0
  location: ^6.0.1
  latlong2: ^0.9.1
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  google_places_flutter: ^2.0.9
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true